### ISSUE TITLE
BUG: nespravne zaradenie pre priloha 16 / paragraf 5 odsek 3

### ISSUE THREAD

**Issue by vlk32** [Institut-zdravotnych-analyz/OSN-Algoritmus-MS-2024#28]
Podla https://www.slov-lex.sk/pravne-predpisy/SK/ZZ/2023/531/20240101?ucinnost=01.08.2024 paragraf 5 odsek 3

> Medicínska služba určená podľa prílohy č. 16, ktorá sa môže vykonať spolu s medicínskymi službami určenými podľa odseku 2 písm. b) až k), je medicínska služba „Identifikácia mŕtveho darcu orgánov“

Grouper vsak zaradi podla tohto odseku aj ked nie je urcena ina medicinska sluzba podla odseku 2.

Testovacie data :
```
id;vek;vek_dni;hmotnost;umela_plucna_ventilacia;diagnozy;vykony;odbornosti;drg;ms
Priloha_16_Y_A;81;0;0;0;Z551~I601~G935~P915;;;A01A;S17-22
```

**Comment by bielovico** [comment]
Citovaný paragraf interpretujeme tak, že medicínska služba podľa prílohy č. 16 sa môže vykonať, aj keď nebola určená žiadna medicínska služba podľa odseku 2 písm. b) až k). V paragrafe sa uvádza `... sa môže vykonať spolu ...`. Nutnosť inej medicínskej služby by bola, pokiaľ by paragraf uvádzal `... sa vykonáva spolu ...` alebo `... sa musí vykonať spolu ...`.

**Comment by vlk32** [comment]
Prosim prediskutujte si Vase tvrdenie aj s prislusnou sekciou na MZ.
Ja som dal rovnaku otazku na pravidelnych strenutiach ku OSN, a tam som mal dojem, ze vyjadrenie je ine. Nasledne diskusia presla na sposob ako vykazat cez davku 274 do poistovne viac ako jednu medicinsku sluzbu.

Ak by sa medicinska sluzba podla prilohy 16. mohla vykovavat aj bez inej medicinskej sluzby, preco by to tvorca vyhlasky vydelil do samostatneho paragrafu a explicitne tam uviedol `... sa môže vykonať spolu ...` ?

**Comment by bielovico** [comment]
Prediskutovali sme a interpretácia zostáva, ako som uvádzal vyššie. K pôvodným motiváciám sa už asi nedostaneme, ale máme na MZ zhodu na intepretácii. Mimochodom, pokiaľ by Vás napadala lepšia formulácia, môžeme ju skúsiť zahrnúť do niektorej z najbližších novelizácii vyhlášky, aby bola interpretácia jasnejšia. Ďakujeme.

**Comment by vlk32** [comment]
Dakujem za informaciu, upravil som podla nej aj moju implementaciu [Arbor AI sk.drg-grouper.eu](https://sk.drg-grouper.eu/durio/1?data=AAI%257C20240811%257C4%257C%257C1%257C1%257C7%257CZ%257C19%257C%257C%257CI634%252CG935%252CI601%252CR402%257C1k2110%252C93091%257C%257C%257C%257C19370804%257C%257CP40707%257C99%257CM%257CP%257CHC)

> Medicínska služba určená podľa prílohy č. 16, ktorá sa môže vykonať spolu s medicínskymi službami určenými podľa odseku 2 písm. b) až k), je medicínska služba „Identifikácia mŕtveho darcu orgánov“

Navrhujem preformulovat na 

> Medicínska služba „Identifikácia mŕtveho darcu orgánov“ určená podľa odseku 3 (príloha č. 16), sa môže vykonať 
> 
> * samostatne ako jediná služba
> * alebo ako súbežná služba spolu s inou medicínskou službou určenou podľa odseku 2 písm. b) až k)
